steps:
  integrationArtifactDownload:
    cpiApiServiceKeyCredentialsId: roverpocServiceKeyCredential
    integrationFlowId: test1
    integrationFlowVersion: 1.0.8
    downloadPath: ./iflows

steps:  
  integrationArtifactUpload:
    cpiApiServiceKeyCredentialsId: roverpocServiceKeyCredential
    integrationFlowId: test1
    integrationFlowName: test1
    packageId: trailiflow
    filePath: ./iflows/test1.zip
